apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: anycompany-api
  description: This is a AnyCompany API Micro Service.  
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: platform

